#ifndef API_CORE_H
#define API_CORE_H

#include "api.h"

#include <stdint.h>

// User must implement
extern const char *api_core_implementation_id; // in PROGMEM
/* Unless overridden in EEPROM, the device ID is generated by appending
   signature bytes and OSCCAL to this array and taking the first 56 bytes. */
extern const uint8_t *api_core_device_id; // in PROGMEM
extern const uint8_t api_core_device_id_len;

// User must invoke as soon as possible after boot
void api_core_recover_reset(void);

extern api_cmd_list api_core;

#endif
