/* Copyright (c) 2015 Antumbra

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program. If not, see <http://www.gnu.org/licenses/>. */

#ifndef API_CORE_H
#define API_CORE_H

#include "api.h"

#include <stdint.h>

// User must implement
extern const char *api_core_implementation_id; // in PROGMEM
/* Unless overridden in EEPROM, the device ID is generated by appending
   signature bytes and OSCCAL to this array and taking the first 56 bytes. */
extern const uint8_t *api_core_device_id; // in PROGMEM
extern const uint8_t api_core_device_id_len;
extern const char *api_core_hardware_id; // in PROGMEM
// Invoked by Core API to fill diagnostic buffer; user must implement. Buffer starts zero-filled.
void api_core_fill_diagnostic(uint8_t *diagbuf);

// User must invoke as soon as possible after boot
void api_core_recover_reset(void);

extern const api_cmd_list api_core;

#endif
